#!/usr/bin/env python3
"""Generate src/core/pinyin_data.cpp from mozillazg/pinyin-data (MIT).

Usage:
    # Download source data first:
    #   curl -L https://raw.githubusercontent.com/mozillazg/pinyin-data/master/pinyin.txt > pinyin.txt
    python tools/gen_pinyin_data.py pinyin.txt
"""
import re, sys, unicodedata
from pathlib import Path

def strip_tones(syllable: str) -> str:
    """Remove tone diacritics; map ü → v (common IME convention)."""
    result = ''
    for ch in unicodedata.normalize('NFD', syllable):
        cat = unicodedata.category(ch)
        if cat == 'Mn':         # combining diacritical mark → drop
            continue
        if ch == 'ü':      # precomposed ü (after NFC) → v
            result += 'v'
        else:
            result += ch
    return result

FIRST, LAST = 0x4E00, 0x9FFF
SIZE = LAST - FIRST + 1  # 20992

def main(src: Path) -> None:
    table = [''] * SIZE
    with src.open(encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            m = re.match(r'U\+([0-9A-Fa-f]+):\s*([^\s#]+)', line)
            if not m:
                continue
            cp = int(m.group(1), 16)
            if cp < FIRST or cp > LAST:
                continue
            syl = strip_tones(m.group(2).split(',')[0])[:6]  # first reading, max 6 chars
            table[cp - FIRST] = syl

    out = Path(__file__).parent.parent / 'src' / 'core' / 'pinyin_data.cpp'
    ROW = 8
    with out.open('w', encoding='utf-8') as f:
        f.write('// AUTO-GENERATED by tools/gen_pinyin_data.py — do not edit.\n')
        f.write('// Source: mozillazg/pinyin-data (MIT License)\n')
        f.write('// Codepoints U+4E00..U+9FFF; index = codepoint - 0x4E00.\n')
        f.write('// Empty string "" = unmapped/rare codepoint.\n')
        f.write('namespace Pinyin {\n')
        f.write(f'extern const char kPinyinTable[{SIZE}][7] = {{\n')
        for i in range(0, SIZE, ROW):
            chunk = [f'"{s}"' for s in table[i:i + ROW]]
            f.write('    ' + ', '.join(chunk) + ',\n')
        f.write('};\n')
        f.write('} // namespace Pinyin\n')

    filled = sum(1 for s in table if s)
    print(f'Entries: {SIZE}, filled: {filled} ({filled * 100 // SIZE}%)', file=sys.stderr)
    print(f'Written: {out}', file=sys.stderr)

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print(f'Usage: python {sys.argv[0]} <pinyin.txt>', file=sys.stderr)
        sys.exit(1)
    main(Path(sys.argv[1]))
